version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/images
      - ./logs:/logs
      - ./static:/static
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./images:/images
      - ./static:/static
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge